---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.heimdall.name }}
  namespace: {{ .Values.heimdall.namespace }}
spec:
  selector:
    matchLabels:
      {{- range $k1, $v1 := .Values.heimdall.labels }}
         {{ $k1 }}: {{ $v1 }}
      {{- end }}
  replicas: {{ .Values.heimdall.replicaCount }} 
  template:
    metadata:
      labels:
        {{- range $k1, $v1 := .Values.heimdall.labels }}
          {{ $k1 }}: {{ $v1 }}
        {{- end }}
    spec:
      {{- if .Values.heimdall.affinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node
                operator: In
                values:
                - {{ .Values.heimdall.affinity.node }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: team
                operator: In
                values:
                - {{ .Values.heimdall.affinity.team }}         
      {{- end }}
      securityContext:
          fsGroup: 1000
      containers:
      - name: {{ .Values.heimdall.name }}
        image: {{ .Values.heimdall.image }}
        imagePullPolicy: IfNotPresent
        {{- if .Values.heimdall.environments }}
        env:
        {{- range $envname , $envvalue := .Values.heimdall.environments }}
        - name: {{ $envname }}
          value: {{ $envvalue }}
        {{- end }}
        {{- end}}
        {{- if .Values.heimdall.security.enabled }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.heimdall.security.allowPrivilegeEscalation  }}
          readOnlyRootFilesystem: {{ .Values.heimdall.security.readOnlyRootFilesystem }}
          runAsUser: {{ .Values.heimdall.security.runAsUser }}
          runAsGroup: {{  .Values.heimdall.security.runAsGroup }}
          capabilities:
            drop:
              {{- range  .Values.heimdall.security.capabilities.drop }} 
              - {{ . }}
              {{- end }} 
            add:
              {{- range  .Values.heimdall.security.capabilities.allow }} 
              - {{ . }}
              {{- end }} 
        {{- end }}

        {{- if .Values.heimdall.volumes }}
        volumeMounts:
        {{- if .Values.heimdall.environments }}
        {{- range $volumename, $mountpath := .Values.heimdall.volumes }}
        - name: {{ $volumename }}
          mountPath: {{ $mountpath.mountpath }}
        {{- if $mountpath.subPath }}
          subPath: {{ $mountpath.subPath }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.heimdall.env}}
        - name: {{ .Values.heimdall.env.name }}
          mountPath: {{ .Values.heimdall.env.path }} 
        {{- end }}
        {{- end }}
        resources:
          requests:
            cpu: {{ .Values.heimdall.resources.requests.cpu }}
            memory: {{ .Values.heimdall.resources.requests.memory }}
          limits:
            cpu: {{ .Values.heimdall.resources.limits.cpu }}
            memory: {{ .Values.heimdall.resources.limits.memory }}
      {{- if .Values.heimdall.volumes }}
      volumes:
        {{- if .Values.heimdall.volumes }}
        {{- range $volumename , $mountpath := .Values.heimdall.volumes }}
        - name: {{ $volumename }}
          persistentVolumeClaim:          
            claimName: {{ $volumename }}
        {{- end }}
        {{- end }}
        - name: sonar-config
          configMap: 
            name: sonar-config
        {{- if .Values.heimdall.env }}
        - name: {{ .Values.heimdall.env.name }}          
          configMap:
            name: {{ .Values.heimdall.env.name }}
      {{- end }}
      {{- end }}
      {{ if .Values.heimdall.imagepullsecret.enabled }}
      imagePullSecrets:
        - name: your secret for private
      {{- end}}
      tolerations:
      - effect: NoSchedule
        key: {{ .Values.heimdall.toleration }}
        operator: Equal
        value: enabled
