{{- $namespace := .Values.openresty.namespace }}
{{- range $name,$config := .Values.openresty.volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-main
  resources:
    requests:
      storage: {{ $config.storage }}
---
{{- end }}
