dbeaver: 
  affinity:
    enabled: false
    team: devops
    node: production
  toleration: production   #prodcution or stage
  strategy:
    enabled: true
    type: RollingUpdate
    maxsurge: 0
    maxunavailble: 1
  name: dbeaver
  image: dbeaver/cloudbeaver
  labels:
    app: dbeaver
    team: devops
    env: prod
  namespace: dbeaver #if your deplyoing on stage , set yournamespace-stage
  environments:
    TZ: "Asia/Tehran" #its a neccessary env , dont ommit it
  security:
    enabled: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop: 
        - ALL
      allow:
        - NET_BIND_SERVICE
        - SYS_NICE
        - SETUID
        - SETGID
  replicaCount: 1
  resources:
    requests:
      cpu: "0.5"
      memory: "128Mi"
    limits:
      cpu: "4" 
      memory: "4048Mi" 
  storageclass: yourstorageclass
  env: {}
  services: #you have to add your second config in template/service.yml
    dbeaver:
      name: dbeaver
      type: ClusterIP
      port: "8978"
      targetport: 8978
  ingress: 
    domain:
      name: dbeaver
      service: dbeaver
      port: 8978
      host: dbeaver.local
