apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sonar-access-policy
  namespace: sonarqube
spec:
  podSelector:
    matchLabels:
      app: sonarqube

  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
  egress:
    - to:
      - namespaceSelector: 
          matchLabels:
            name: sonarqube
        podSelector:
          matchLabels:
            app: sonar-postgres

    - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
    - to:
        - ipBlock:
            cidr: 192.168.1.15
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sonarpsql-access-policy
  namespace: sonarqube
spec:
  podSelector:
    matchLabels:
      app: sonar-postgres

  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - namespaceSelector: 
          matchLabels:
            name: sonarqube
        podSelector:
          matchLabels:
           app: sonarqube

  egress:
    - to:
      - namespaceSelector: 
          matchLabels:
            name: sonarqube
        podSelector:
          matchLabels:
              app: sonarqube
    - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
