apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudbeaver
  namespace: {{ .Values.dbeaver.namespace }}
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-main
  resources:
    requests:
      storage: 5G
