openresty: 
  affinity:
    enabled: false
    team: devops
    node: production
  toleration: production  #prodcution or stage
  name: openresty
  imagepullsecret:
    enabled: false
  image: openresty/openresty:nginx-openresty
  labels:
    app: openresty
    team: devops
    env: production
  namespace: heimdall #if your deplyoing on stage , set yournamespace-stage
  environments:
    TZ: "Asia/Tehran" #its a neccessary env , dont ommit it
  security:
    enabled: false
    allowPrivilegeEscalation: true
    readOnlyRootFilesystem: false
    runAsUser: 1
    runAsGroup: 1 
    capabilities:
      drop: 
        - ALL
      allow:
        - NET_BIND_SERVICE
        - SYS_NICE
        - SETUID
        - SETGID
  replicaCount: 1
  resources:
    requests:
      cpu: "0.5"
      memory: "128Mi"
    limits:
      cpu: "2" 
      memory: "2048Mi" 
  storageclass: yourstorageclass
  env: {}
  volumes: {}  #open template/pvc and add a section for each of volume definition below.
  services: #you have to add your second config in template/service.yml
    openresty:
      name: openresty-svc
      type: ClusterIP
      port: "80"
      targetport: 80
  ingress: 
    domain:
      name: {}
      service: {}
      port: {}
      host: {}
